# Generated by Django 3.0.4 on 2020-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='path',
            name='url_short',
            field=models.CharField(max_length=50),
        ),
    ]
